FROM yxakuo/buildpack-deps:base_py3
# py3_AP_library

MAINTAINER Allen tGuo

RUN pip install --no-cache-dir \
    contextlib2 \
    raven \
    colorama \
    mysqlclient

RUN pip install --no-cache-dir \
    requests \
    lxml \
    redis \
    vine \
    amqp \
    kombu \
    six \
    pytz \
    tzlocal \
    apscheduler \
    numpy \
    python-dateutil \
    pandas \
    astropy \
    bs4 \
    sqlalchemy \
    pymysql


RUN pip install --no-cache-dir \
    tushare