FROM yxakuo/buildpack-deps:base_py3
# py3_AP_library

MAINTAINER Allen tGuo

RUN pip install contextlib2 \
 && pip install raven

RUN pip install requests \
 && pip install lxml \
 && pip install redis \
 && pip install vine \
 && pip install amqp \
 && pip install kombu \
 && pip install six \
 && pip install pytz \
 && pip install tzlocal \
 && pip install apscheduler \
 && pip install numpy \
 && pip install python-dateutil \
 && pip install pandas \
 && pip install astropy \
 && pip install bs4

RUN pip install tushare