FROM yxakuo/base_py3

MAINTAINER Allen tGuo

RUN pip install --upgrade pip

RUN pip install contextlib2 \
 && pip install raven

RUN pip install requests \
 && pip install lxml \
 && pip install redis \
 && pip install vine \
 && pip install amqp \
 && pip install kombu \
 && pip install six \
 && pip install pytz \
 && pip install tzlocal \
 && pip install apscheduler \
 && pip install numpy \
 && pip install python-dateutil \
 && pip install pandas \
 && pip install astropy

RUN pip install tushare