FROM python:3.6
# py3_ArticleProcess

MAINTAINER Allen tGuo

USER root

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#RUN mkdir -p ~/.pip && touch ~/.pip/pip.conf && echo "[global]" > ~/.pip/pip.conf && echo "index-url = https://pypi.douban.com/simple" >> ~/.pip/pip.conf
